language: php

php:
  - 5.4
  - 5.5  
  - 5.6
  - 7.0

env:
  - DB=mysql

before_script:
  - composer install
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS software;" -uroot; fi

script: phpunit --configuration phpunit_$DB.xml --coverage-text
